name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: netcore-unit-testing/web-api/
    - name: Build
      run: dotnet build /home/runner/work/unit-testing-aspnetcore-webapi/unit-testing-aspnetcore-webapi/netcore-unit-testing/web-api/web-api/web-api.csproj --no-restore
